const actionTypes = {
    GET_HOME: 'GET_HOME',
    SET_CUR_SONG_ID: 'SET_CUR_SONG_ID',
    SET_CUR_SONG_DATA: 'SET_CUR_SONG_DATA',
    SET_CUR_ALBUM_ID: 'SET_CUR_ALBUM_ID',
    SET_RECENT: 'SET_RECENT',

    //music
    PLAY: "PLAY",
    SET_ALBUM: 'SET_ALBUM',
    PLAYLIST: 'PLAYLIST',
    SEARCH: 'SEARCH',
    ZERO_SCROLTOP: 'ZERO_SCROLTOP',
    CURRENT_WIDTH: 'CURRENT_WIDTH'


}
export default actionTypes